version: '3.8'

volumes:
  db:

services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    restart: always
    environment:
      - MYSQL_DATABASE=game
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - '3306:3306'
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
